### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by saraswat** [philipperemy/financial-news-dataset#2]
Can you clarify who owns this data, and under what license is it being made available? Thanks! (The text in there right now kind of steps around this.)

**Comment by philipperemy** [comment]
@saraswat The licence is not clear here. That's why I stayed a bit vague. Probably a lawyer would be able to answer those questions. And I would be interested to know too.

All what I can say is:
- This dataset was scraped from public available data from Reuters and Bloomberg.
- It was used in at least two scientific papers (Ding et al. 2014 and 2015).
